using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;

public partial class _Default : System.Web.UI.Page
{
    FrontEnd f = new FrontEnd();
    Validator z = new Validator();
    protected void Page_Load(object sender, EventArgs e)
    {
        f.getHeader(ulHeader);
        f.getFooter(ulfooter);
        if (!IsPostBack)
        {
            lblCheck.Visible = false;
        }
    }

    protected void Submit_Click(object sender, EventArgs e)
    {
        lblCheck.Visible = false;
        string Query = "SELECT * FROM Login WHERE UserName='" + username.Text + "'";
        DataTable dt = z.FillDataTable(Query);
        if (dt.Rows.Count > 0)
        {
            string salt = z.Salt(dt.Rows[0][1].ToString());
            string password = salt;
                string subject = "Reset Password";
                string body = "This Is An AutoGenerated Password";
                z.Send(dt.Rows[0][0].ToString(), password, subject, body);

                lblCheck.Visible = true;
                lblCheck.Text = "Your Reset Password Has Been Send";
                lblCheck.Font.Bold = true;
                lblCheck.ForeColor = System.Drawing.Color.Green;
                username.Enabled = false;
            
        }
        else
        {
            lblCheck.Visible = true;
            lblCheck.Text = "This User Name Does Not Exist";
            lblCheck.Font.Bold = true;
            lblCheck.ForeColor = System.Drawing.Color.Red;
            username.Text = "Username@max.com";
            return;
        }
    }
}